services:
  app:
    image: 'webdevops/php-nginx:8.2'
    container_name: booking-app-backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - '8000:80'
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
    depends_on:
      - db
      - python-api
    networks:
      - app-network

  db:
    image: 'mysql:8.0'
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking-app-backend
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    networks:
      - app-network


  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: booking-app-backend-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - app-network

  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile 
    container_name: python-api
    volumes:
    - ./python-api:/usr/src/app
    ports:
      - '5000:5000'
    networks:
      - app-network      
    depends_on:
      - db              

volumes:
  dbdata:

networks:
  app-network:   # Định nghĩa mạng app-network
    driver: bridge
